### ISSUE TITLE
error when retriving size of MPI

### ISSUE THREAD

**Issue by danilobenozzo** [dbbs-lab/bsb-hdf5#35]
I have this error when compiling a conf file
```bash
Creating storage from config.
Traceback (most recent call last):
  File "/home/dbenozzo/dbbs_lab/dbbs_test/bin/bsb", line 8, in <module>
    sys.exit(handle_cli())
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/cli/__init__.py", line 11, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/cli/__init__.py", line 31, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/cli/commands/__init__.py", line 99, in execute_handler
    self.handler(context)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/cli/commands/_commands.py", line 141, in handler
    network = Scaffold(cfg)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/core.py", line 146, in __init__
    self._bootstrap(config, storage, clear=clear)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/core.py", line 182, in _bootstrap
    storage = Storage(
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/storage/__init__.py", line 156, in __init__
    self._engine = create_engine(engine, root, self._comm)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/storage/__init__.py", line 102, in create_engine
    return get_engine_support(name)["Engine"](root, comm)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-hdf5/bsb_hdf5/__init__.py", line 95, in __init__
    self._lock = MPILock.sync(comm._comm)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/services/mpilock.py", line 123, in sync
    return MockedWindowController(comm, master)
  File "/home/dbenozzo/dbbs_lab/repos/bsb-core/bsb/services/mpilock.py", line 13, in __init__
    self._size = comm.get_size()
AttributeError: 'mpi4py.MPI.Intracomm' object has no attribute 'get_size'. Did you mean: 'Get_size'?
```

I don't know why but if this https://github.com/dbbs-lab/bsb-hdf5/blob/694417e8e0c341bf8ac432f1cf136ba1bd8d2520/bsb_hdf5/__init__.py#L95C9-L95C45

becomes `self._lock = MPILock.sync(comm)` then it works

**Comment by drodarie** [comment]
You are missing the ``mpilock`` python library here.
Try to reinstall ``bsb-core`` with the parallel flag:
```bash
pip install bsb-core[parallel]
```
 or if you cloned bsb-core, run this into your bsb-core folder
```bash
pip install -e.[parallel]
```
